services:
  nginx:
    image: public.ecr.aws/docker/library/nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # - ../frontend/build/client:/home/ishocon/webapp/public:ro
    ports:
      - "8080:80"
    depends_on:
      - webapp
  webapp:
    build:
      context: ../webapp/python
      dockerfile: ../../development/dockerfiles/Dockerfile.python
    image: webapp-python
    expose:
      - 8080
    volumes:
      - ../webapp/sql:/home/ishocon/webapp/sql
    working_dir: /home/ishocon/webapp/python
    depends_on:
      db:
        condition: service_healthy
    environment:
      ISHOCON_DB_HOST: db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: public.ecr.aws/docker/library/mysql:8
    environment:
      ENV: local-dev
      MYSQL_DATABASE: ishocon3
      MYSQL_USER: ishocon
      MYSQL_ROOT_PASSWORD: ishocon
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ../webapp/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ishocon -pishocon
      start_period: 60s
