version: "3"

includes:
  python: ./taskfile/python/
  ruby: ./taskfile/ruby/

tasks:
  initialize:
    cmds:
      - curl -X POST http://localhost:8080/api/initialize

  benchmark:
    cmds:
      - go build -o benchmark && ./benchmark --log-level info
    dir: ./benchmark/
