FROM python:3.13

WORKDIR /home/ishocon/webapp/python

RUN apt-get update && apt-get install --no-install-recommends -y \
  default-mysql-client-core=1.1.1 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY ./pyproject.toml ./pyproject.toml

RUN pip install uv && uv sync # --locked --no-dev

COPY . .

CMD ["/home/ishocon/webapp/python/.venv/bin/gunicorn", "--bind", "0.0.0.0:8080"]
