# frozen_string_literal: true

source 'https://rubygems.org'

group :development do
  gem 'rubocop', '~> 1.81.7'
end

gem 'bcrypt', '~> 3.1'
gem 'chunky_png', '~> 1.4'
gem 'mysql2', '~> 0.5.7'
gem 'puma', '~> 7.1'
gem 'rackup', '~> 2.2'
gem 'redis', '~> 5.3'
gem 'rqrcode', '~> 3.1'
gem 'sinatra', '~> 4.2'
gem 'sinatra-activerecord', '~> 2.0'
gem 'sinatra-param', '~> 1.6'
gem 'ulid', '~> 1.4'
